# Generated by Django 5.1.1 on 2026-04-03 15:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hemis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetakeCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=32)),
                ('semester_no', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('open', 'Ochiq'), ('closed', 'Yopiq'), ('archived', 'Arxivlangan')], default='draft', max_length=32)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetakeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('in_review', "Ko'rib chiqilmoqda"), ('partially_approved', 'Qisman tasdiqlangan'), ('approved', 'Tasdiqlangan'), ('returned', 'Qaytarilgan'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('declared_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('accountant_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('accountant_comment', models.TextField(blank=True, default='')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='retake/contracts/')),
                ('contract_original_name', models.CharField(blank=True, default='', max_length=255)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='retake/receipts/')),
                ('receipt_original_name', models.CharField(blank=True, default='', max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis.hemisstudentsnapshot')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='retake.retakecycle')),
            ],
        ),
        migrations.CreateModel(
            name='RetakeApplicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_control_type', models.CharField(default='other', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('submitted_to_accounting', 'Buxgalteriyaga yuborilgan'), ('payment_rejected', "To'lov rad etilgan"), ('payment_approved', "To'lov tasdiqlangan"), ('awaiting_supervisor', "Rahbar tasdig'ini kutmoqda"), ('supervisor_returned', 'Rahbar qaytargan'), ('approved_for_grouping', 'Guruhlashga tayyor'), ('grouped', 'Guruhlangan'), ('scheduled', 'Jadvalga kiritilgan'), ('grade_entry_open', 'Baholash ochiq'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=32)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='retake.retakeapplication')),
                ('debt_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hemis.hemisstudentdebt')),
                ('subject_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis.hemissubjectsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='RetakeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=32)),
                ('file', models.FileField(upload_to='retake/items/')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='retake.retakeapplicationitem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
