# Generated by Django 5.1.1 on 2026-04-03 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemis', '0001_initial'),
        ('retake', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='retakedocument',
            old_name='item',
            new_name='application_item',
        ),
        migrations.CreateModel(
            name='AssessmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_type', models.CharField(default='other', max_length=16)),
                ('scheduled_at', models.DateTimeField()),
                ('room', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('open', 'Ochiq'), ('closed', 'Yopiq')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('teacher_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_no', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('open', 'Ochiq'), ('submitted', 'Topshirilgan'), ('locked', 'Bloklangan')], default='draft', max_length=16)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sheet', to='retake.assessmentschedule')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=16)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reviews', to='retake.retakeapplicationitem')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetakeGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_control_type', models.CharField(default='other', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('application_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_membership', to='retake.retakeapplicationitem')),
                ('student_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis.hemisstudentsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='retake.examsheet')),
                ('student_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis.hemisstudentsnapshot')),
                ('group_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_entries', to='retake.retakegroupmembership')),
            ],
        ),
        migrations.CreateModel(
            name='RetakeSubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('capacity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('active', 'Faol'), ('completed', 'Yakunlangan')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='retake.retakecycle')),
                ('subject_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis.hemissubjectsnapshot')),
                ('teacher_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacherprofile')),
            ],
        ),
        migrations.AddField(
            model_name='retakegroupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='retake.retakesubjectgroup'),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='retake.retakesubjectgroup')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentschedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schedules', to='retake.retakesubjectgroup'),
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('object_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=64)),
                ('from_status', models.CharField(default='', max_length=64)),
                ('to_status', models.CharField(default='', max_length=64)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
