# Generated by Django 5.1.1 on 2026-04-04 11:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retake', '0002_rename_item_retakedocument_application_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retakecycle',
            name='max_allowed_credits',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5),
        ),
    ]
