# Generated by Django 5.1.1 on 2026-04-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retake', '0003_retakecycle_max_allowed_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retakecycle',
            name='semester_no',
        ),
    ]
