# Generated by Django 5.1.1 on 2026-04-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retake', '0004_remove_retakecycle_semester_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentschedule',
            name='pair_number',
            field=models.IntegerField(blank=True, help_text='Juftlik (para) raqami', null=True),
        ),
        migrations.AlterField(
            model_name='assessmentschedule',
            name='room',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
