# Generated by Django 5.1.1 on 2026-04-05 05:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retake', '0005_add_pair_number_to_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetakeAssessmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_type', models.CharField(max_length=32, unique=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
