# Generated by Django 5.1.1 on 2026-04-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retake', '0006_retakeassessmentconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSheetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('html_content', models.TextField(help_text='Qaydnoma HTML kodi')),
                ('css_content', models.TextField(blank=True, default='', help_text='Qaydnoma CSS kodi')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
