# Generated by Django 5.1.1 on 2026-04-05 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_assignment_allow_late_assignment_is_active_and_more'),
        ('retake', '0007_examsheettemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='retakesubjectgroup',
            name='lms_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retake_groups', to='lms.course'),
        ),
    ]
