# Generated by Django 5.1.1 on 2026-04-11 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemis', '0003_hemisstudentdebt_control_type'),
        ('lms', '0011_certificate_template_version'),
        ('retake', '0008_retakesubjectgroup_lms_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentschedule',
            name='student_group_name',
            field=models.CharField(blank=True, default='', help_text="HEMIS talabalar guruhi nomi (masalan: MT-21-1). Bo'sh bo'lsa — barcha.", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentschedule',
            unique_together={('group', 'student_group_name', 'control_type')},
        ),
        migrations.CreateModel(
            name='DBManagerFacultyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(help_text='HemisStudentSnapshot.faculty_name bilan mos kelishi kerak', max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_db_manager_faculties', to=settings.AUTH_USER_MODEL)),
                ('db_manager_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_manager_faculty_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MB Menejeri Fakultet Biriktiruvi',
                'verbose_name_plural': 'MB Menejerlari Fakultet Biriktiruvi',
                'unique_together': {('db_manager_user', 'faculty_name')},
            },
        ),
        migrations.CreateModel(
            name='RetakeCourseEnrollmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemis_student_group', models.CharField(default='', help_text='Student snapshot ning group_name qiymati', max_length=255)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_logs', to='retake.retakesubjectgroup')),
                ('lms_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retake_enrollment_logs', to='lms.course')),
                ('student_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis.hemisstudentsnapshot')),
            ],
            options={
                'verbose_name': 'Retake LMS Enrollment Log',
                'unique_together': {('group', 'lms_course', 'student_snapshot')},
            },
        ),
    ]
