# Generated by Django 5.1.1 on 2026-04-12 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retake', '0009_unified_retake_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRegistratorFacultyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(help_text='HemisStudentSnapshot.faculty_name bilan mos kelishi kerak', max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_registrator_faculties', to=settings.AUTH_USER_MODEL)),
                ('service_registrator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_registrator_faculty_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xizmat registratori fakultet biriktiruvi',
                'verbose_name_plural': 'Xizmat registratorlari fakultet biriktiruvlari',
                'unique_together': {('service_registrator_user', 'faculty_name')},
            },
        ),
    ]
