# Generated by Django 5.1.1 on 2026-04-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retake', '0010_service_registrator_faculty_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retakecycle',
            options={'verbose_name': 'Qayta topshirish sikli', 'verbose_name_plural': 'Qayta topshirish sikllari'},
        ),
        migrations.AlterUniqueTogether(
            name='retakecycle',
            unique_together={('academic_year', 'name')},
        ),
    ]
