# Generated by Django 5.1.1 on 2026-04-03 15:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TEACHER', "O'qituvchi"), ('STUDENT', 'Talaba'), ('ACADEMIC_BOARD', "O'quv bo'limi"), ('DIRECTION', 'Rahbariyat'), ('REGISTRATOR', 'Registrator ofisi'), ('RET_REGISTRATOR', "Registrator (xizmat ko'rsatish)"), ('RET_ACCOUNTING', 'Registrator (buxgalteriya)'), ('RET_SUPERVISOR', "Registrator boshlig'i"), ('RET_DB_MANAGER', 'Registrator (MB menejeri)')], default='STUDENT', max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('student_id_number', models.CharField(max_length=20, unique=True)),
                ('university', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('faculty_name', models.CharField(default='', max_length=255)),
                ('group_name', models.CharField(default='', max_length=255)),
                ('specialty_name', models.CharField(default='', max_length=255)),
                ('education_lang', models.CharField(default='', max_length=100)),
                ('level', models.CharField(default='', max_length=100)),
                ('education_form', models.CharField(default='', max_length=100)),
                ('education_type', models.CharField(default='', max_length=100)),
                ('payment_form', models.CharField(default='', max_length=100)),
                ('student_status', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='')),
                ('bstu_token', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('university', models.CharField(default='', max_length=255)),
                ('department', models.CharField(default='', max_length=255)),
                ('hemis_id', models.CharField(blank=True, default='', max_length=64)),
                ('hemis_uuid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('hemis_position', models.CharField(default='', max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('auth_provider', models.CharField(blank=True, default='', max_length=32)),
                ('profile_payload', models.JSONField(blank=True, default=dict)),
                ('experience_years', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
