# Generated by Django 5.1.1 on 2026-04-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='accommodation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='social_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='avatar_full_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
