# Generated by Django 5.1.1 on 2026-04-07 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_accommodation_studentprofile_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('section', models.CharField(choices=[('MAIN', 'Asosiy'), ('RETAKE', 'Retake'), ('ADMIN', 'Admin'), ('LEGACY', 'Legacy')], default='MAIN', max_length=20)),
                ('icon_lucide', models.CharField(default='layout-dashboard', max_length=80)),
                ('spa_path', models.CharField(blank=True, default='', max_length=255)),
                ('url_name', models.CharField(blank=True, default='', max_length=255)),
                ('external_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Sidebar menu',
                'verbose_name_plural': 'Sidebar menus',
                'ordering': ['section', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SidebarMenuAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TEACHER', "O'qituvchi"), ('STUDENT', 'Talaba'), ('ACADEMIC_BOARD', "O'quv bo'limi"), ('DIRECTION', 'Rahbariyat'), ('REGISTRATOR', 'Registrator ofisi'), ('RET_REGISTRATOR', "Registrator (xizmat ko'rsatish)"), ('RET_ACCOUNTING', 'Registrator (buxgalteriya)'), ('RET_SUPERVISOR', "Registrator boshlig'i"), ('RET_DB_MANAGER', 'Registrator (MB menejeri)')], max_length=50)),
                ('order_index', models.PositiveIntegerField(default=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_access', to='users.sidebarmenu')),
            ],
            options={
                'verbose_name': 'Sidebar menu access',
                'verbose_name_plural': 'Sidebar menu access rules',
                'ordering': ['role', 'order_index', 'menu__label'],
                'constraints': [models.UniqueConstraint(fields=('menu', 'role'), name='uniq_sidebar_menu_role')],
            },
        ),
    ]
