# Generated by Django 5.1.1 on 2026-04-07 15:25

from django.db import migrations


MENU_DEFINITIONS = [
    {
        "key": "dashboard",
        "label": "Dashboard",
        "section": "MAIN",
        "icon_lucide": "layout-dashboard",
        "spa_path": "/",
        "description": "Asosiy boshqaruv paneli",
    },
    {
        "key": "courses",
        "label": "Kurslar",
        "section": "MAIN",
        "icon_lucide": "book-open",
        "spa_path": "/courses",
        "description": "Kurslar va o'quv kontenti",
    },
    {
        "key": "tests",
        "label": "Testlar",
        "section": "MAIN",
        "icon_lucide": "clipboard-edit",
        "spa_path": "/tests",
        "description": "Nazorat va test modullari",
    },
    {
        "key": "grades",
        "label": "Baholar",
        "section": "MAIN",
        "icon_lucide": "bar-chart-3",
        "spa_path": "/grades",
        "description": "Talaba baholari va natijalari",
    },
    {
        "key": "notifications",
        "label": "Bildirishnomalar",
        "section": "MAIN",
        "icon_lucide": "bell",
        "spa_path": "/notifications",
        "description": "Tizim bildirishnomalari",
    },
    {
        "key": "messages",
        "label": "Xabarlar",
        "section": "MAIN",
        "icon_lucide": "message-circle",
        "spa_path": "/messages",
        "description": "Foydalanuvchilar o'rtasidagi muloqot",
    },
    {
        "key": "profile",
        "label": "Profil",
        "section": "MAIN",
        "icon_lucide": "user-circle-2",
        "spa_path": "/profile",
        "description": "Profil va hisob sozlamalari",
    },
    {
        "key": "retake",
        "label": "Retake",
        "section": "RETAKE",
        "icon_lucide": "refresh-cw",
        "spa_path": "/retake",
        "description": "Retake arizalari va jarayonlari",
    },
    {
        "key": "super-admin",
        "label": "Super Admin",
        "section": "ADMIN",
        "icon_lucide": "shield",
        "spa_path": "/super-admin",
        "description": "Super admin uchun umumiy SPA panel",
    },
    {
        "key": "django-admin",
        "label": "Django Admin",
        "section": "ADMIN",
        "icon_lucide": "file-code",
        "external_url": "/admin/",
        "description": "Django admin paneli",
    },
    {
        "key": "sidebar-menus-admin",
        "label": "Sidebar Menular",
        "section": "ADMIN",
        "icon_lucide": "pencil-ruler",
        "spa_path": "/super-admin/sidebar/menus",
        "description": "Sidebar menyularini frontend ichida boshqarish",
    },
    {
        "key": "sidebar-access-admin",
        "label": "Sidebar Ruxsatlari",
        "section": "ADMIN",
        "icon_lucide": "toggle-right",
        "spa_path": "/super-admin/sidebar/access",
        "description": "Role bo'yicha menu access va tartibni frontend ichida boshqarish",
    },
    {
        "key": "legacy-admin-dashboard",
        "label": "Legacy Admin Panel",
        "section": "ADMIN",
        "icon_lucide": "shield",
        "spa_path": "/legacy/lms/admin-dashboard/",
        "description": "Eski LMS admin paneli",
    },
    {
        "key": "legacy-create-teacher",
        "label": "O'qituvchi yaratish",
        "section": "ADMIN",
        "icon_lucide": "user-plus",
        "spa_path": "/legacy/lms/admin/teachers/create/",
        "description": "Legacy o'qituvchi yaratish formasi",
    },
    {
        "key": "legacy-create-student",
        "label": "Talaba yaratish",
        "section": "ADMIN",
        "icon_lucide": "graduation-cap",
        "spa_path": "/legacy/lms/admin/students/create/",
        "description": "Legacy talaba yaratish formasi",
    },
    {
        "key": "legacy-retake-dashboard",
        "label": "Retake dashboard",
        "section": "RETAKE",
        "icon_lucide": "layout-dashboard",
        "spa_path": "/legacy/retake/dashboard/",
        "description": "Legacy retake boshqaruv paneli",
    },
    {
        "key": "legacy-retake-search-student",
        "label": "Talaba qidirish",
        "section": "RETAKE",
        "icon_lucide": "user-check",
        "spa_path": "/legacy/retake/search-student/",
        "description": "Retake ariza uchun talaba qidirish",
    },
    {
        "key": "legacy-retake-applications",
        "label": "Retake arizalari",
        "section": "RETAKE",
        "icon_lucide": "notebook-pen",
        "spa_path": "/legacy/retake/applications/",
        "description": "Retake arizalari ro'yxati",
    },
    {
        "key": "legacy-retake-accounting",
        "label": "Buxgalteriya tekshiruvi",
        "section": "RETAKE",
        "icon_lucide": "wallet",
        "spa_path": "/legacy/retake/accounting/list/",
        "description": "To'lovlarni buxgalteriya tekshiradi",
    },
    {
        "key": "legacy-retake-supervisor",
        "label": "Supervisor tasdiqlari",
        "section": "RETAKE",
        "icon_lucide": "check-circle-2",
        "spa_path": "/legacy/retake/supervisor/list/",
        "description": "Supervisor ko'rib chiqish navbati",
    },
    {
        "key": "legacy-retake-groups",
        "label": "Retake guruhlari",
        "section": "RETAKE",
        "icon_lucide": "users",
        "spa_path": "/legacy/retake/db-manager/groups/",
        "description": "Retake guruhlarini boshqarish",
    },
    {
        "key": "legacy-retake-schedules",
        "label": "Dars jadvallari",
        "section": "RETAKE",
        "icon_lucide": "calendar-days",
        "spa_path": "/legacy/retake/db-manager/schedules/",
        "description": "Retake dars jadvallari",
    },
    {
        "key": "legacy-retake-exam-calendar",
        "label": "Imtihon kalendari",
        "section": "RETAKE",
        "icon_lucide": "calendar-check",
        "spa_path": "/legacy/retake/db-manager/exam-calendar/",
        "description": "Retake imtihon kalendari",
    },
    {
        "key": "legacy-retake-cycles",
        "label": "Retake sikllari",
        "section": "RETAKE",
        "icon_lucide": "calendar-range",
        "spa_path": "/legacy/retake/cycles/",
        "description": "Retake davrlari va sikllari",
    },
    {
        "key": "legacy-retake-sync",
        "label": "Retake sync",
        "section": "RETAKE",
        "icon_lucide": "refresh-cw",
        "spa_path": "/legacy/retake/sync/",
        "description": "HEMIS bilan retake sinxronizatsiyasi",
    },
    {
        "key": "legacy-retake-teacher-groups",
        "label": "Retake teacher groups",
        "section": "RETAKE",
        "icon_lucide": "users",
        "spa_path": "/legacy/retake/teacher/groups/",
        "description": "Retake o'qituvchi guruhlari",
    },
]


ROLE_ACCESS = {
    "SUPER_ADMIN": [
        (10, "dashboard"),
        (20, "super-admin"),
        (30, "courses"),
        (40, "tests"),
        (50, "grades"),
        (60, "notifications"),
        (70, "messages"),
        (80, "profile"),
        (100, "retake"),
        (110, "legacy-retake-dashboard"),
        (120, "legacy-retake-search-student"),
        (130, "legacy-retake-applications"),
        (140, "legacy-retake-accounting"),
        (150, "legacy-retake-supervisor"),
        (160, "legacy-retake-groups"),
        (170, "legacy-retake-schedules"),
        (180, "legacy-retake-exam-calendar"),
        (190, "legacy-retake-cycles"),
        (200, "legacy-retake-sync"),
        (210, "legacy-retake-teacher-groups"),
        (300, "django-admin"),
        (310, "sidebar-menus-admin"),
        (320, "sidebar-access-admin"),
        (330, "legacy-admin-dashboard"),
        (340, "legacy-create-teacher"),
        (350, "legacy-create-student"),
    ],
    "TEACHER": [
        (10, "dashboard"),
        (20, "courses"),
        (30, "tests"),
        (40, "notifications"),
        (50, "messages"),
        (60, "profile"),
        (100, "legacy-retake-teacher-groups"),
    ],
    "STUDENT": [
        (10, "dashboard"),
        (20, "courses"),
        (30, "tests"),
        (40, "grades"),
        (50, "retake"),
        (60, "notifications"),
        (70, "messages"),
        (80, "profile"),
    ],
    "ACADEMIC_BOARD": [
        (10, "dashboard"),
        (20, "courses"),
        (30, "tests"),
        (40, "grades"),
        (50, "notifications"),
        (60, "messages"),
        (70, "profile"),
    ],
    "DIRECTION": [
        (10, "dashboard"),
        (20, "courses"),
        (30, "tests"),
        (40, "grades"),
        (50, "notifications"),
        (60, "messages"),
        (70, "profile"),
    ],
    "REGISTRATOR": [
        (10, "dashboard"),
        (20, "courses"),
        (30, "grades"),
        (40, "notifications"),
        (50, "messages"),
        (60, "profile"),
    ],
    "RET_REGISTRATOR": [
        (10, "dashboard"),
        (20, "retake"),
        (30, "legacy-retake-dashboard"),
        (40, "legacy-retake-search-student"),
        (50, "legacy-retake-applications"),
        (60, "legacy-retake-cycles"),
        (70, "notifications"),
        (80, "messages"),
        (90, "profile"),
    ],
    "RET_ACCOUNTING": [
        (10, "dashboard"),
        (20, "retake"),
        (30, "legacy-retake-dashboard"),
        (40, "legacy-retake-accounting"),
        (50, "legacy-retake-applications"),
        (60, "notifications"),
        (70, "messages"),
        (80, "profile"),
    ],
    "RET_SUPERVISOR": [
        (10, "dashboard"),
        (20, "retake"),
        (30, "legacy-retake-dashboard"),
        (40, "legacy-retake-supervisor"),
        (50, "legacy-retake-applications"),
        (60, "notifications"),
        (70, "messages"),
        (80, "profile"),
    ],
    "RET_DB_MANAGER": [
        (10, "dashboard"),
        (20, "retake"),
        (30, "legacy-retake-dashboard"),
        (40, "legacy-retake-groups"),
        (50, "legacy-retake-schedules"),
        (60, "legacy-retake-exam-calendar"),
        (70, "legacy-retake-cycles"),
        (80, "legacy-retake-sync"),
        (90, "notifications"),
        (100, "messages"),
        (110, "profile"),
    ],
}


def seed_sidebar_navigation(apps, schema_editor):
    SidebarMenu = apps.get_model("users", "SidebarMenu")
    SidebarMenuAccess = apps.get_model("users", "SidebarMenuAccess")

    managed_keys = []
    for menu in MENU_DEFINITIONS:
        managed_keys.append(menu["key"])
        SidebarMenu.objects.update_or_create(
            key=menu["key"],
            defaults={
                "label": menu["label"],
                "section": menu["section"],
                "icon_lucide": menu["icon_lucide"],
                "spa_path": menu.get("spa_path", ""),
                "url_name": menu.get("url_name", ""),
                "external_url": menu.get("external_url", ""),
                "is_enabled": True,
                "description": menu.get("description", ""),
            },
        )

    menu_map = {
        menu.key: menu
        for menu in SidebarMenu.objects.filter(key__in=managed_keys)
    }

    for role, items in ROLE_ACCESS.items():
        for order_index, menu_key in items:
            SidebarMenuAccess.objects.update_or_create(
                menu=menu_map[menu_key],
                role=role,
                defaults={
                    "order_index": order_index,
                    "is_visible": True,
                },
            )


def remove_sidebar_navigation(apps, schema_editor):
    SidebarMenu = apps.get_model("users", "SidebarMenu")
    SidebarMenuAccess = apps.get_model("users", "SidebarMenuAccess")
    managed_keys = [menu["key"] for menu in MENU_DEFINITIONS]
    SidebarMenuAccess.objects.filter(menu__key__in=managed_keys).delete()
    SidebarMenu.objects.filter(key__in=managed_keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_sidebarmenu_sidebarmenuaccess"),
    ]

    operations = [
        migrations.RunPython(seed_sidebar_navigation, remove_sidebar_navigation),
    ]
