# Generated by Codex on 2026-04-08

from django.db import migrations


MENU_PATH_MAP = {
    "legacy-admin-dashboard": "/admin/dashboard",
    "legacy-create-teacher": "/admin/teachers/create",
    "legacy-create-student": "/admin/students/create",
    "legacy-retake-dashboard": "/retake",
    "legacy-retake-search-student": "/retake/search-student",
    "legacy-retake-applications": "/retake/applications",
    "legacy-retake-accounting": "/retake/applications",
    "legacy-retake-supervisor": "/retake/applications",
    "legacy-retake-groups": "/retake/groups",
    "legacy-retake-schedules": "/retake/schedules",
    "legacy-retake-exam-calendar": "/retake/exam-calendar",
    "legacy-retake-cycles": "/retake/cycles",
    "legacy-retake-sync": "/retake/sync",
    "legacy-retake-teacher-groups": "/retake/teacher/groups",
}


def forwards(apps, schema_editor):
    SidebarMenu = apps.get_model("users", "SidebarMenu")
    for key, spa_path in MENU_PATH_MAP.items():
        SidebarMenu.objects.filter(key=key).update(
            spa_path=spa_path,
            url_name="",
            external_url="",
        )


def backwards(apps, schema_editor):
    # Keep current SPA mapping on rollback too; older legacy paths are deprecated.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_move_sidebar_admin_links_to_spa"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
