# Generated by Django 5.1.1 on 2026-04-23 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemis', '0004_hemisroomsnapshot_building_code_floor'),
        ('users', '0018_rename_retake_applications_sidebar_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='hemis_snapshot',
            field=models.OneToOneField(blank=True, help_text="HEMIS snapshot bilan to'g'ridan-to'g'ri bog'liq", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to='hemis.hemisstudentsnapshot'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hemis_student_id',
            field=models.BigIntegerField(blank=True, help_text='HEMIS ichki talaba ID (HemisStudentSnapshot.hemis_student_id bilan mos keladi)', null=True, unique=True),
        ),
    ]
