from django.urls import path

from . import api_views, api_views_document


urlpatterns = [
    path("dashboard/", api_views.dashboard_summary, name="api_dashboard_summary"),
    path("admin/dashboard/", api_views.admin_dashboard_summary, name="api_admin_dashboard_summary"),
    path("admin/teachers/create/", api_views.admin_create_teacher, name="api_admin_create_teacher"),
    path("admin/students/create/", api_views.admin_create_student, name="api_admin_create_student"),
    path("courses/", api_views.courses_list, name="api_courses_list"),
    path("courses/<int:course_id>/", api_views.course_detail, name="api_course_detail"),
    path("tests/", api_views.tests_list, name="api_tests_list"),
    path("tests/<int:test_id>/take/", api_views.test_take_payload, name="api_test_take_payload"),
    path("tests/<int:test_id>/submit/", api_views.test_submit, name="api_test_submit"),
    path("tests/<int:test_id>/face-verify/", api_views.test_face_verify, name="api_test_face_verify"),
    path("tests/<int:test_id>/result/", api_views.test_result, name="api_test_result"),
    path("teacher/courses/", api_views.teacher_courses, name="api_teacher_courses"),
    path("teacher/courses/create/", api_views.teacher_course_create, name="api_teacher_course_create"),
    path("teacher/courses/<int:course_id>/manage/", api_views.teacher_course_manage, name="api_teacher_course_manage"),
    path("teacher/courses/<int:course_id>/update/", api_views.teacher_course_update, name="api_teacher_course_update"),
    path("teacher/courses/<int:course_id>/delete/", api_views.teacher_course_delete, name="api_teacher_course_delete"),
    path("teacher/courses/<int:course_id>/sections/create/", api_views.teacher_section_create, name="api_teacher_section_create"),
    path("teacher/sections/<int:section_id>/update/", api_views.teacher_section_update, name="api_teacher_section_update"),
    path("teacher/sections/<int:section_id>/delete/", api_views.teacher_section_delete, name="api_teacher_section_delete"),
    path("teacher/courses/<int:course_id>/sections/reorder/", api_views.teacher_sections_reorder, name="api_teacher_sections_reorder"),
    path("teacher/sections/<int:section_id>/resources/create/", api_views.teacher_resource_create, name="api_teacher_resource_create"),
    path("teacher/resources/<int:resource_id>/update/", api_views.teacher_resource_update, name="api_teacher_resource_update"),
    path("teacher/resources/<int:resource_id>/replace-file/", api_views.teacher_resource_replace_file, name="api_teacher_resource_replace_file"),
    path("teacher/resources/<int:resource_id>/rename/", api_views.teacher_resource_rename, name="api_teacher_resource_rename"),
    path("teacher/resources/<int:resource_id>/stats/", api_views.teacher_resource_stats, name="teacher_resource_stats"),
    path("teacher/resources/<int:resource_id>/delete/", api_views.teacher_resource_delete, name="api_teacher_resource_delete"),
    path("teacher/sections/<int:section_id>/resources/reorder/", api_views.teacher_resources_reorder, name="api_teacher_resources_reorder"),
    path("resources/<int:resource_id>/viewed/", api_views.resource_mark_viewed, name="api_resource_viewed"),
    path("resources/<int:resource_id>/complete/", api_views.resource_mark_completed, name="api_resource_complete"),
    path("resources/<int:resource_id>/chapters/<int:chapter_id>/", api_views.resource_book_chapter, name="api_book_chapter"),
    path("teacher/resources/<int:resource_id>/chapters/save/", api_views.teacher_book_chapter_save, name="api_teacher_book_chapter_save"),
    path("teacher/resources/<int:resource_id>/chapters/<int:chapter_id>/delete/", api_views.teacher_book_chapter_delete, name="api_teacher_book_chapter_delete"),
    path("teacher/resources/<int:resource_id>/glossary/save/", api_views.teacher_glossary_entry_save, name="api_teacher_glossary_save"),
    path("teacher/resources/<int:resource_id>/glossary/<int:entry_id>/delete/", api_views.teacher_glossary_entry_delete, name="api_teacher_glossary_delete"),
    path("teacher/resources/<int:resource_id>/folder/upload/", api_views.teacher_folder_file_upload, name="api_teacher_folder_upload"),
    path("teacher/resources/<int:resource_id>/folder/<int:file_id>/delete/", api_views.teacher_folder_file_delete, name="api_teacher_folder_file_delete"),
    path("teacher/courses/<int:course_id>/enrollments/search/", api_views.teacher_enrollment_search, name="api_teacher_enrollment_search"),
    path("teacher/courses/<int:course_id>/enrollments/add/", api_views.teacher_enrollment_add, name="api_teacher_enrollment_add"),
    path("teacher/enrollments/<int:enrollment_id>/delete/", api_views.teacher_enrollment_delete, name="api_teacher_enrollment_delete"),
    path("teacher/courses/<int:course_id>/assignments/create/", api_views.teacher_assignment_create, name="api_teacher_assignment_create"),
    path("teacher/assignments/<int:assignment_id>/update/", api_views.teacher_assignment_update, name="api_teacher_assignment_update"),
    path("teacher/assignments/<int:assignment_id>/delete/", api_views.teacher_assignment_delete, name="api_teacher_assignment_delete"),
    path("teacher/tests/create/", api_views.teacher_test_create, name="api_teacher_test_create"),
    path("teacher/tests/<int:test_id>/", api_views.teacher_test_detail, name="api_teacher_test_detail"),
    path("teacher/tests/<int:test_id>/update/", api_views.teacher_test_update, name="api_teacher_test_update"),
    path("teacher/tests/<int:test_id>/delete/", api_views.teacher_test_delete, name="api_teacher_test_delete"),
    path("teacher/tests/<int:test_id>/questions/", api_views.teacher_test_questions, name="api_teacher_test_questions"),
    path("teacher/tests/<int:test_id>/questions/list/", api_views.teacher_test_questions_list, name="api_teacher_test_questions_list"),
    path("teacher/questions/<int:question_id>/update/", api_views.teacher_question_update, name="api_teacher_question_update"),
    path("teacher/questions/<int:question_id>/delete/", api_views.teacher_question_delete, name="api_teacher_question_delete"),
    path("proctor-log/", api_views.proctor_log, name="api_proctor_log"),
    path("notifications/", api_views.notifications_list, name="api_notifications_list"),
    path("notifications/<int:notif_id>/read/", api_views.notification_read, name="api_notification_read"),
    path("notifications/read-all/", api_views.notifications_read_all, name="api_notifications_read_all"),
    path("login-alerts/", api_views.login_alerts, name="api_login_alerts"),
    path("assignments/<int:assignment_id>/extension-request/", api_views.extension_request_create, name="api_extension_request_create"),
    path("admin/extension-requests/", api_views.admin_extension_requests_list, name="api_extension_requests_list"),
    path("admin/extension-requests/<int:request_id>/review/", api_views.admin_extension_request_review, name="api_extension_request_review"),
    path("courses/<int:course_id>/meetings/create/", api_views.meeting_create, name="api_meeting_create"),
    path("meetings/<int:meeting_id>/delete/", api_views.meeting_delete, name="api_meeting_delete"),
    path("courses/<int:course_id>/forum/topics/", api_views.forum_topics_list, name="api_forum_topics_list"),
    path("courses/<int:course_id>/forum/topics/create/", api_views.forum_topic_create, name="api_forum_topic_create"),
    path("forum/topics/<int:topic_id>/", api_views.forum_topic_detail, name="api_forum_topic_detail"),
    path("forum/topics/<int:topic_id>/reply/", api_views.forum_topic_reply, name="api_forum_topic_reply"),
    path("student/grades/", api_views.student_grades, name="api_student_grades"),
    path("teacher/courses/<int:course_id>/gradebook/", api_views.teacher_gradebook_detail, name="api_teacher_gradebook_detail"),
    path("teacher/courses/<int:course_id>/gradebook/setup/", api_views.teacher_gradebook_setup, name="api_teacher_gradebook_setup"),
    path("teacher/courses/<int:course_id>/gradebook/save/", api_views.teacher_gradebook_save, name="api_teacher_gradebook_save"),
    path("teacher/courses/<int:course_id>/gradebook/import-test/<int:test_id>/", api_views.teacher_gradebook_import_test, name="api_teacher_gradebook_import_test"),
    path("assignments/<int:assignment_id>/", api_views.assignment_detail, name="api_assignment_detail"),
    path("assignments/<int:assignment_id>/submit/", api_views.assignment_submit, name="api_assignment_submit"),
    path("submissions/<int:submission_id>/grade/", api_views.submission_grade, name="api_submission_grade"),
    path("courses/<int:course_id>/certificate/check/", api_views.course_certificate_check, name="api_course_certificate_check"),
    path("courses/<int:course_id>/certificate/download/", api_views.course_certificate_download, name="api_course_certificate_download"),
    path("verify/<str:serial>/", api_views.api_certificate_verify, name="api_certificate_verify"),
    path("teacher/courses/<int:course_id>/certificate/template/save/", api_views.teacher_certificate_template_save, name="api_teacher_certificate_template_save"),
    path("teacher/courses/<int:course_id>/certificate/trigger/save/", api_views.teacher_certificate_trigger_save, name="api_teacher_certificate_trigger_save"),
    path("teacher/courses/<int:course_id>/certificate/trigger/<int:trigger_id>/delete/", api_views.teacher_certificate_trigger_delete, name="api_teacher_certificate_trigger_delete"),

    # Document editor endpoints
    path("teacher/certificate-template/<int:template_id>/docx/load/", api_views_document.template_docx_load, name="api_template_docx_load"),
    path("teacher/certificate-template/<int:template_id>/docx/save/", api_views_document.template_docx_save, name="api_template_docx_save"),
    path("teacher/certificate-template/<int:template_id>/versions/", api_views_document.template_versions_list, name="api_template_versions_list"),
    path("teacher/certificate-template/<int:template_id>/versions/<int:version_id>/restore/", api_views_document.template_version_restore, name="api_template_version_restore"),

    # Resource file viewer endpoint
    path("resources/<int:resource_id>/file/load/", api_views_document.resource_file_load, name="api_resource_file_load"),
]
