from .dashboard import *
from .courses import *
from .enrollments import *
from .tests import *
from .assignments import *
from .forums import *
from .gradebook import *
from .resources import *
from .notifications import *
