# Generated by Django 5.1.1 on 2026-04-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='direct_messages/'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
