# Generated by Django 5.1.1 on 2026-04-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_assignment_allow_late_assignment_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
