# Generated by Django 5.1.1 on 2026-04-09 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_course_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionresource',
            name='resource_type',
            field=models.CharField(choices=[('file', 'Fayl'), ('link', 'Havola'), ('video', 'Video'), ('text', 'Matn'), ('certificate', 'Sertifikat')], default='file', max_length=16),
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/')),
                ('html_template', models.TextField(help_text='HTML template for certificate. Use {{ student_name }}, {{ course_name }}, {{ date }}, {{ serial_number }} placeholders.')),
                ('css_style', models.TextField(blank=True, default='', help_text='Custom CSS for certificate')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='lms.course')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('course_complete', 'Kurs tugallanganda'), ('section_complete', 'Mavzu tugallanganda'), ('test_score', "Test natijasiga ko'ra")], max_length=32)),
                ('min_score_percentage', models.IntegerField(blank=True, help_text='Minimum score percentage for test trigger', null=True)),
                ('message_if_locked', models.TextField(blank=True, default='Sertifikat olish uchun barcha shartlarni bajaring.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_triggers', to='lms.course')),
                ('target_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.section')),
                ('target_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.test')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.certificatetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('qr_data', models.CharField(blank=True, max_length=255)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_certificates', to='lms.course')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.certificatetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
