# Generated by Django 4.2 on 2026-04-10 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0004_added_certificate_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionresource',
            name='audio_transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sectionresource',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sectionresource',
            name='embed_height',
            field=models.CharField(default='500px', max_length=16),
        ),
        migrations.AddField(
            model_name='sectionresource',
            name='embed_width',
            field=models.CharField(default='100%', max_length=16),
        ),
        migrations.AddField(
            model_name='sectionresource',
            name='estimated_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionresource',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionresource',
            name='h5p_embed_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sectionresource',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sectionresource',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sectionresource',
            name='open_in_new_tab',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sectionresource',
            name='require_completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sectionresource',
            name='scorm_entry_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sectionresource',
            name='scorm_version',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='sectionresource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sectionresource',
            name='video_poster_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='sectionresource',
            name='video_source',
            field=models.CharField(choices=[('url', 'URL'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('file', 'Fayl')], default='url', max_length=16),
        ),
        migrations.AlterField(
            model_name='sectionresource',
            name='resource_type',
            field=models.CharField(choices=[('file', 'Fayl'), ('link', 'Havola'), ('video', 'Video'), ('text', 'Matn sahifasi'), ('audio', 'Audio'), ('embed', 'Embed / iframe'), ('h5p', 'H5P interaktiv'), ('scorm', 'SCORM paketi'), ('folder', 'Papka'), ('book', 'Kitob'), ('glossary', 'Glossariy'), ('certificate', 'Sertifikat')], default='file', max_length=16),
        ),
        migrations.AlterField(
            model_name='sectionresource',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='GlossaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossary_entries', to='lms.sectionresource')),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='FolderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='folder_files/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_files', to='lms.sectionresource')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='lms.sectionresource')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResourceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='lms.sectionresource')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('resource', 'student')},
            },
        ),
    ]
