# Generated by Django 4.2 on 2026-04-10 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0005_moodle_like_resources_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentStudentDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeadlineExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Talaba sababi')),
                ('requested_deadline', models.DateTimeField(help_text="Talaba so'ragan yangi muddat")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], db_index=True, default='pending', max_length=16)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('approved_deadline', models.DateTimeField(blank=True, help_text='Admin tasdiqlagan yangi muddat', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('course_enrolled', "Kursga qo'shildi"), ('deadline_warning', 'Muddat yaqinlashmoqda'), ('deadline_overdue', "Muddat o'tib ketdi"), ('deadline_extended', 'Muddat uzaytirildi'), ('extension_approved', "So'rov tasdiqlandi"), ('extension_rejected', "So'rov rad etildi"), ('system', 'Tizim xabari')], db_index=True, default='system', max_length=32),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=8),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='lms_notific_user_id_b4d901_idx'),
        ),
        migrations.AddField(
            model_name='deadlineextensionrequest',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='lms.assignment'),
        ),
        migrations.AddField(
            model_name='deadlineextensionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_extensions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deadlineextensionrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentstudentdeadline',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_deadlines', to='lms.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentstudentdeadline',
            name='set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_deadlines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentstudentdeadline',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_deadlines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='deadlineextensionrequest',
            unique_together={('student', 'assignment')},
        ),
        migrations.AlterUniqueTogether(
            name='assignmentstudentdeadline',
            unique_together={('student', 'assignment')},
        ),
    ]
