# Generated by Django 5.1.1 on 2026-04-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_add_notification_type_deadline_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='docx_file',
            field=models.FileField(blank=True, help_text='DOCX shablon: {{student_name}}, {{course_name}}, {{certificate_date}}, {{serial_number}}, {{hours}}, {{score}}, {{max_score}}, {{issued_by}}, {{position}}, {{verify_url}}, {{qr_placeholder}}', null=True, upload_to='certificate_templates/docx/'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='generation_mode',
            field=models.CharField(choices=[('html', 'HTML (xhtml2pdf)'), ('docx', 'DOCX (LibreOffice)')], default='docx', help_text='DOCX — yuqori sifatli PDF; HTML — eski usul.', max_length=8),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='hours_per_course',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='institution_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='issued_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='position',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='html_template',
            field=models.TextField(blank=True, default='', help_text="generation_mode=html bo'lsa. {{ student_name }}, {{ course_name }}, {{ date }}, {{ serial_number }}"),
        ),
    ]
