# Generated by Django 5.1.1 on 2026-04-10 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_certificate_pdf_cache_invalidation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='docx_file',
            field=models.FileField(blank=True, help_text='DOCX shablon (LibreOffice orqali PDF). Placeholderlar: {{student_name}}, {{course_name}}, {{certificate_date}}, {{serial_number}}, {{hours}}, {{score}}, {{max_score}}, {{issued_by}}, {{position}}, {{verify_url}}, {{qr_placeholder}}, {{institution_name}}', null=True, upload_to='certificate_templates/docx/'),
        ),
        migrations.CreateModel(
            name='CertificateTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docx_file', models.FileField(upload_to='certificate_templates/versions/')),
                ('version_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='lms.certificatetemplate')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('template', 'version_number')},
            },
        ),
    ]
