# Generated by Django 5.1.1 on 2026-04-03 15:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HemisCurriculumSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemis_curriculum_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('specialty_code', models.CharField(blank=True, default='', max_length=64)),
                ('specialty_name', models.CharField(blank=True, default='', max_length=255)),
                ('department_code', models.CharField(blank=True, default='', max_length=64)),
                ('department_name', models.CharField(blank=True, default='', max_length=255)),
                ('education_type_name', models.CharField(blank=True, default='', max_length=255)),
                ('education_form_name', models.CharField(blank=True, default='', max_length=255)),
                ('education_year_name', models.CharField(blank=True, default='', max_length=255)),
                ('semester_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HemisRoomSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemis_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('building_name', models.CharField(blank=True, default='', max_length=255)),
                ('capacity', models.IntegerField(default=0)),
                ('room_type', models.CharField(blank=True, default='', max_length=128)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HemisStudentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemis_student_id', models.BigIntegerField(unique=True)),
                ('student_id_number', models.CharField(blank=True, default='', max_length=64)),
                ('pinfl', models.CharField(blank=True, default='', max_length=32)),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, default='', max_length=255)),
                ('faculty_name', models.CharField(blank=True, default='', max_length=255)),
                ('specialty_name', models.CharField(blank=True, default='', max_length=255)),
                ('group_name', models.CharField(blank=True, default='', max_length=255)),
                ('semester_code', models.CharField(blank=True, default='', max_length=64)),
                ('semester_name', models.CharField(blank=True, default='', max_length=255)),
                ('curriculum_id', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HemisSubjectSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemis_subject_id', models.BigIntegerField(unique=True)),
                ('curriculum_subject_id', models.BigIntegerField(blank=True, null=True)),
                ('subject_code', models.CharField(blank=True, default='', max_length=64)),
                ('subject_name', models.CharField(max_length=255)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('semester_code', models.CharField(blank=True, default='', max_length=64)),
                ('semester_name', models.CharField(blank=True, default='', max_length=255)),
                ('primary_exam_type', models.CharField(blank=True, default='', max_length=64)),
                ('exam_types', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HemisStudentDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_year', models.CharField(blank=True, default='', max_length=64)),
                ('semester_label', models.CharField(blank=True, default='', max_length=64)),
                ('exam_type_label', models.CharField(blank=True, default='', max_length=128)),
                ('total_point', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='hemis.hemisstudentsnapshot')),
                ('subject_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='hemis.hemissubjectsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='HemisSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('running', 'Jarayonda'), ('success', 'Muvaffaqiyatli'), ('partial', 'Qisman'), ('failed', 'Muvaffaqiyatsiz')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('processed_count', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
