# Generated by Django 5.1.1 on 2026-04-04 12:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hemiscurriculumsnapshot',
            name='education_form_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hemiscurriculumsnapshot',
            name='education_type_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hemiscurriculumsnapshot',
            name='education_year_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hemisstudentdebt',
            name='debt_status',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hemisstudentdebt',
            name='required_point',
            field=models.DecimalField(decimal_places=2, default=Decimal('55.00'), max_digits=6),
        ),
    ]
