# Generated by Django 5.1.1 on 2026-04-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemis', '0002_hemiscurriculumsnapshot_education_form_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hemisstudentdebt',
            name='control_type',
            field=models.CharField(default='other', max_length=32),
        ),
    ]
